// UniwaApp/nextday-operations-prepare/moc-app2/frontend/src/components/PlaceSelector.vue
<template>
   <Select
    :model-value="selectedPlaceId || ''"
    @update:model-value="handlePlaceChange"
    > <SelectTrigger :class="className"> <SelectValue :placeholder="placeholder" /> </SelectTrigger>
    <SelectContent
      > <SelectItem
        v-for="place in filteredPlaces"
        :key="place.id"
        :value="place.id"
        > {{ place.name }} </SelectItem
      > </SelectContent
    > </Select
  >
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Select from '@/components/ui/select.vue';
import SelectContent from '@/components/ui/select-content.vue';
import SelectItem from '@/components/ui/select-item.vue';
import SelectTrigger from '@/components/ui/select-trigger.vue';
import SelectValue from '@/components/ui/select-value.vue';
import type { Place } from '@/types';
import { PLACE_TYPE } from '@/lib/enums/place-type';
import { getDisplayName, getLogicalName, isEnumCode, type EnumCode } from '@/lib/utils/enum-utils';
import { LABELS } from '@/lib/constants/labels';

interface PlaceSelectorProps {
  places: Place[];
  selectedPlaceId: string | null;
  type: EnumCode<typeof PLACE_TYPE>;
  className?: string;
}

const props = defineProps<PlaceSelectorProps>();

const emit = defineEmits<{
  'update:selectedPlaceId': [placeId: string];
}>();

const filteredPlaces = computed(() =>
  props.places.filter((place) =>
    isEnumCode(PLACE_TYPE, place.type, getLogicalName(PLACE_TYPE, props.type))
  )
);

const logicalName = computed(() => getLogicalName(PLACE_TYPE, props.type));
const placeholder = computed(() =>
  logicalName.value ? getDisplayName(PLACE_TYPE, logicalName.value) + 'を選択' : ''
);

const handlePlaceChange = (placeId: string) => {
  emit('update:selectedPlaceId', placeId);
};
</script>

// UniwaApp/operations-prepare/components/inventory/place-selector.tsx
'use client';

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import type { Place } from '@/lib/types';
import { PLACE_TYPE } from '@/lib/schemas/enums/place-type';
import { getDisplayName, getLogicalName, isEnumCode, type EnumCode } from '@/lib/utils/enum-utils';

interface PlaceSelectorProps {
  places: Place[];
  selectedPlaceId: string | null;
  onPlaceChange: (placeId: string) => void;
  type: EnumCode<typeof PLACE_TYPE>;
  className?: string;
}

export function PlaceSelector({
  places,
  selectedPlaceId,
  onPlaceChange,
  type,
  className,
}: PlaceSelectorProps) {
  const filteredPlaces = places.filter(place => isEnumCode(PLACE_TYPE, place.place_type, getLogicalName(PLACE_TYPE, type)));
  
  const logicalName = getLogicalName(PLACE_TYPE, type);
  const placeholder = (logicalName ? getDisplayName(PLACE_TYPE, logicalName) : '') + 'を選択';
  
  return (
    <Select
      value={selectedPlaceId || ''}
      onValueChange={onPlaceChange}
    >
      <SelectTrigger className={className}>
        <SelectValue placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent>
        {filteredPlaces.map((place) => (
          <SelectItem key={place.place_id} value={place.place_id}>
            {place.place_name}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}
