// UniwaApp/operations-prepare/components/status/status-overview.tsx
'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import type { Item, InventoryStatus } from '@/lib/types';

interface StatusOverviewProps {
  date: string;
  items: Item[];
  inventoryStatuses: InventoryStatus[];
}

export function StatusOverview({ date, items, inventoryStatuses }: StatusOverviewProps) {
  const [showActionNeeded, setShowActionNeeded] = useState(true);

  const getItemStatus = (itemId: string) => {
    return inventoryStatuses.find((status) => status.itemId === itemId);
  };

  const needsAction = (status: InventoryStatus | undefined) => {
    if (!status) return false;

    return (
      status.checkStatus === 'unchecked' ||
      status.restockStatus === 'needs-restock' ||
      status.createStatus === 'needs-creation' ||
      status.orderStatus === 'needs-order'
    );
  };

  const filteredItems = showActionNeeded
    ? items.filter((item) => needsAction(getItemStatus(item.id)))
    : items;

  const renderStatusBadge = (status: string) => {
    switch (status) {
      case 'unchecked':
        return <Badge variant="outline">未確認</Badge>;
      case 'checking':
        return <Badge variant="secondary">確認中</Badge>;
      case 'checked':
        return <Badge className="bg-green-500">確認済</Badge>;
      case 'not-required':
        return <Badge variant="outline">不要</Badge>;
      case 'needs-restock':
        return <Badge variant="secondary">要補充</Badge>;
      case 'restocked':
        return <Badge className="bg-green-500">補充済</Badge>;
      case 'needs-creation':
        return <Badge variant="secondary">要作成</Badge>;
      case 'created':
        return <Badge className="bg-green-500">作成済</Badge>;
      case 'creation-requested':
        return <Badge className="bg-blue-500">作成依頼済</Badge>;
      case 'needs-order':
        return <Badge variant="secondary">要発注</Badge>;
      case 'ordered':
        return <Badge className="bg-green-500">発注依頼済</Badge>;
      default:
        return null;
    }
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex justify-between items-center">
          <CardTitle className="text-xl">準備状況一覧</CardTitle>
          <div className="flex items-center space-x-2">
            <Checkbox
              id="show-action-needed"
              checked={showActionNeeded}
              onCheckedChange={(checked) => setShowActionNeeded(!!checked)}
            />
            <Label htmlFor="show-action-needed" className="text-sm cursor-pointer">
              要対応のみ表示
            </Label>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="check">
          <TabsList className="grid grid-cols-4 mb-4">
            <TabsTrigger value="check">確認</TabsTrigger>
            <TabsTrigger value="restock">補充</TabsTrigger>
            <TabsTrigger value="create">作成</TabsTrigger>
            <TabsTrigger value="order">発注</TabsTrigger>
          </TabsList>

          <ScrollArea className="h-[calc(100vh-300px)]">
            <TabsContent value="check" className="mt-0">
              {filteredItems.map((item) => {
                const status = getItemStatus(item.id);
                return (
                  <div key={item.id} className="py-2 border-b">
                    <div className="flex justify-between items-center">
                      <span className="font-medium">{item.name}</span>
                      {status && renderStatusBadge(status.checkStatus)}
                    </div>
                    {status && (
                      <div className="text-sm text-muted-foreground mt-1">
                        在庫数: {status.currentStock || 0}
                      </div>
                    )}
                  </div>
                );
              })}
            </TabsContent>

            <TabsContent value="restock" className="mt-0">
              {filteredItems.map((item) => {
                const status = getItemStatus(item.id);
                return (
                  <div key={item.id} className="py-2 border-b">
                    <div className="flex justify-between items-center">
                      <span className="font-medium">{item.name}</span>
                      {status && renderStatusBadge(status.restockStatus)}
                    </div>
                    {status && (
                      <div className="flex justify-between text-sm mt-1">
                        <span className="text-muted-foreground">
                          補充数: {status.restockAmount || 0}
                        </span>
                      </div>
                    )}
                  </div>
                );
              })}
            </TabsContent>

            <TabsContent value="create" className="mt-0">
              {filteredItems.map((item) => {
                const status = getItemStatus(item.id);
                return (
                  <div key={item.id} className="py-2 border-b">
                    <div className="flex justify-between items-center">
                      <span className="font-medium">{item.name}</span>
                      {status && renderStatusBadge(status.createStatus)}
                    </div>
                    {status && status.notes && (
                      <div className="text-sm text-muted-foreground mt-1 truncate">
                        {status.notes}
                      </div>
                    )}
                  </div>
                );
              })}
            </TabsContent>

            <TabsContent value="order" className="mt-0">
              {filteredItems.map((item) => {
                const status = getItemStatus(item.id);
                return (
                  <div key={item.id} className="py-2 border-b">
                    <div className="flex justify-between items-center">
                      <span className="font-medium">{item.name}</span>
                      {status && renderStatusBadge(status.orderStatus)}
                    </div>
                    {status && status.notes && (
                      <div className="text-sm text-muted-foreground mt-1 truncate">
                        {status.notes}
                      </div>
                    )}
                  </div>
                );
              })}
            </TabsContent>
          </ScrollArea>
        </Tabs>
      </CardContent>
    </Card>
  );
}

// UniwaApp/nextday-operations-prepare/moc-app2/frontend/src/components/status/StatusOverview.vue
<template>
  <div class="w-full space-y-4">
    <Card v-for="item in items" :key="item.id" class="relative w-full">
      <CardHeader class="pb-2">
        <CardTitle class="text-lg">{{ item.name }}</CardTitle>
        <CardDescription v-if="item.description">{{ item.description }}</CardDescription>
      </CardHeader>
      <CardContent>
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">在庫確認</span>
            <Badge :variant="getInventoryStatusVariant(item)" class="text-sm">
              {{ getInventoryStatusLabel(item) }}
            </Badge>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">補充</span>
            <Badge :variant="getReplenishmentStatusVariant(item)" class="text-sm">
              {{ getReplenishmentStatusLabel(item) }}
            </Badge>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">作成</span>
            <Badge :variant="getPreparationStatusVariant(item)" class="text-sm">
              {{ getPreparationStatusLabel(item) }}
            </Badge>
          </div>

          <div class="flex items-center justify-between">
            <span class="text-sm text-muted-foreground">発注依頼</span>
            <Badge :variant="getOrderRequestStatusVariant(item)" class="text-sm">
              {{ getOrderRequestStatusLabel(item) }}
            </Badge>
          </div>

          <div
            v-if="getInventoryStatus(item)"
            class="mt-2 pt-2 border-t border-border/50 space-y-1"
          >
            <div class="text-xs text-muted-foreground">
              在庫数: {{ getInventoryStatus(item)?.inventoryCount ?? 0 }}
            </div>

            <div class="text-xs text-muted-foreground">
              補充数: {{ getInventoryStatus(item)?.replenishmentCount ?? 0 }}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

<script setup lang="ts">
import Card from "@/components/ui/card.vue";
import CardHeader from "@/components/ui/card-header.vue";
import CardTitle from "@/components/ui/card-title.vue";
import CardDescription from "@/components/ui/card-description.vue";
import CardContent from "@/components/ui/card-content.vue";
import Badge from "@/components/ui/badge.vue";
import type { Item, InventoryStatus } from "@/types";
import { INVENTORY_STATUS } from "@/lib/enums/inventory-status";
import { REPLENISHMENT_STATUS } from "@/lib/enums/replenishment-status";
import { PREPARATION_STATUS } from "@/lib/enums/preparation-status";
import { ORDER_REQUEST_STATUS } from "@/lib/enums/order-request-status";
import { getCode, isEnumCode, getDisplayName, toEnumCode } from "@/lib/utils/enum-utils";

interface StatusOverviewProps {
  date: string;
  items: Item[];
  inventoryStatuses: InventoryStatus[];
}

const props = defineProps<StatusOverviewProps>();

const getInventoryStatus = (item: Item): InventoryStatus | undefined => {
  return props.inventoryStatuses.find(
    (status) => status.itemId === item.id || status.item?.id === item.id
  );
};

const getInventoryStatusVariant = (
  item: Item
): "default" | "secondary" | "destructive" | "outline" => {
  const status = getInventoryStatus(item);
  if (!status) return "outline";
  const checkStatus = toEnumCode(
    INVENTORY_STATUS,
    status.inventoryCheckStatus ?? getCode(INVENTORY_STATUS, "UNCONFIRMED")
  );
  return isEnumCode(INVENTORY_STATUS, checkStatus, "CONFIRMED") ? "default" : "secondary";
};

const getInventoryStatusLabel = (item: Item): string => {
  const status = getInventoryStatus(item);
  if (!status) return "未確認";
  const checkStatus = toEnumCode(
    INVENTORY_STATUS,
    status.inventoryCheckStatus ?? getCode(INVENTORY_STATUS, "UNCONFIRMED")
  );
  return getDisplayName(INVENTORY_STATUS, checkStatus);
};

const getReplenishmentStatusVariant = (
  item: Item
): "default" | "secondary" | "destructive" | "outline" => {
  const status = getInventoryStatus(item);
  if (!status) return "outline";
  const replenishmentStatus = toEnumCode(
    REPLENISHMENT_STATUS,
    status.replenishmentStatus ?? getCode(REPLENISHMENT_STATUS, "NOT_REQUIRED")
  );
  if (isEnumCode(REPLENISHMENT_STATUS, replenishmentStatus, "REQUIRED"))
    return "destructive";
  if (isEnumCode(REPLENISHMENT_STATUS, replenishmentStatus, "COMPLETED"))
    return "default";
  return "secondary";
};

const getReplenishmentStatusLabel = (item: Item): string => {
  const status = getInventoryStatus(item);
  if (!status) return "補充不要";
  const replenishmentStatus = toEnumCode(
    REPLENISHMENT_STATUS,
    status.replenishmentStatus ?? getCode(REPLENISHMENT_STATUS, "NOT_REQUIRED")
  );
  return getDisplayName(REPLENISHMENT_STATUS, replenishmentStatus);
};

const getPreparationStatusVariant = (
  item: Item
): "default" | "secondary" | "destructive" | "outline" => {
  const status = getInventoryStatus(item);
  if (!status) return "outline";
  const preparationStatus = toEnumCode(
    PREPARATION_STATUS,
    status.preparationStatus ?? getCode(PREPARATION_STATUS, "NOT_REQUIRED")
  );
  if (isEnumCode(PREPARATION_STATUS, preparationStatus, "REQUIRED")) return "destructive";
  if (isEnumCode(PREPARATION_STATUS, preparationStatus, "COMPLETED")) return "default";
  return "secondary";
};

const getPreparationStatusLabel = (item: Item): string => {
  const status = getInventoryStatus(item);
  if (!status) return "作成不要";
  const preparationStatus = toEnumCode(
    PREPARATION_STATUS,
    status.preparationStatus ?? getCode(PREPARATION_STATUS, "NOT_REQUIRED")
  );
  return getDisplayName(PREPARATION_STATUS, preparationStatus);
};

const getOrderRequestStatusVariant = (
  item: Item
): "default" | "secondary" | "destructive" | "outline" => {
  const status = getInventoryStatus(item);
  if (!status) return "outline";
  const orderRequestStatus = toEnumCode(
    ORDER_REQUEST_STATUS,
    status.orderRequestStatus ?? getCode(ORDER_REQUEST_STATUS, "NOT_REQUIRED")
  );
  if (isEnumCode(ORDER_REQUEST_STATUS, orderRequestStatus, "REQUIRED"))
    return "destructive";
  if (isEnumCode(ORDER_REQUEST_STATUS, orderRequestStatus, "REQUESTED")) return "default";
  return "secondary";
};

const getOrderRequestStatusLabel = (item: Item): string => {
  const status = getInventoryStatus(item);
  if (!status) return "発注不要";
  const orderRequestStatus = toEnumCode(
    ORDER_REQUEST_STATUS,
    status.orderRequestStatus ?? getCode(ORDER_REQUEST_STATUS, "NOT_REQUIRED")
  );
  return getDisplayName(ORDER_REQUEST_STATUS, orderRequestStatus);
};
</script>
