// UniwaApp/nextday-operations-prepare/moc-app2/frontend/src/components/layout/MainLayout.vue
<template>

  <div class="flex flex-col min-h-screen">
     <!-- Header -->
    <header class="sticky top-0 z-50 bg-background border-b border-border">

      <div class="container flex items-center justify-between h-14 px-4">

        <div class="flex items-center gap-3">
           <Sheet
            :open="isOpen"
            @update:open="setIsOpen"
            > <SheetTrigger as-child
              > <Button
                variant="ghost"
                size="icon"
                class="md:hidden"
                > <Menu class="h-5 w-5" /> <span class="sr-only">メニュー</span> </Button
              > </SheetTrigger
            > <SheetContent
              side="left"
              class="p-0"
              :style="{ paddingLeft: 'env(safe-area-inset-left)' }"
              >
              <div class="flex flex-col h-full">

                <div
                  class="p-4 border-b flex justify-between items-center"
                  :style="{ paddingTop: 'max(1rem, env(safe-area-inset-top))' }"
                >

                  <h2 class="text-lg font-medium">メニュー</h2>
                   <Button
                    variant="ghost"
                    size="icon"
                    @click="setIsOpen(false)"
                    > <X class="h-5 w-5" /> </Button
                  >
                </div>
                 <ScrollArea class="flex-1"
                  >
                  <nav class="px-2 py-4">

                    <ul class="space-y-2">

                      <li
                        v-for="item in menuItems"
                        :key="item.path"
                      >
                         <RouterLink
                          :to="item.path"
                          @click="setIsOpen(false)"
                          :class="[
                            'flex items-center gap-3 px-3 py-2 rounded-md text-sm transition-colors',
                            $route.path === item.path
                              ? 'bg-primary text-primary-foreground'
                              : 'hover:bg-secondary',
                          ]"
                          > <component
                            :is="item.iconComponent"
                            class="h-5 w-5"
                          /> {{ item.name }} </RouterLink
                        >
                      </li>

                    </ul>

                  </nav>
                   </ScrollArea
                >
              </div>
               </SheetContent
            > </Sheet
          >
          <h1 class="text-lg font-semibold">営業準備アプリ</h1>

        </div>

        <div class="flex items-center gap-2">
           <Button
            variant="ghost"
            size="icon"
            @click="toggleTheme"
            > <Sun
              v-if="isDark"
              class="h-5 w-5"
            /> <Moon
              v-else
              class="h-5 w-5"
            /> <span class="sr-only">テーマ切替</span> </Button
          >
        </div>

      </div>

    </header>
     <!-- Main content -->
    <main class="flex-1 container px-4 py-4 max-w-lg mx-auto"> <slot /> </main>
     <!-- Mobile navigation -->
    <div
      class="md:hidden sticky bottom-0 z-40 bg-background border-t border-border bottom-nav-safe"
    >

      <nav class="flex items-center justify-around h-16">
         <RouterLink
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          :class="[
            'flex flex-col items-center justify-center w-full h-full text-xs',
            $route.path === item.path ? 'text-primary' : 'text-muted-foreground',
          ]"
          > <component
            :is="item.iconComponent"
            class="h-5 w-5"
          /> <span class="mt-1">{{ item.name }}</span
          > </RouterLink
        >
      </nav>

    </div>

  </div>

</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRoute, RouterLink } from 'vue-router';
import { useDark, useToggle } from '@vueuse/core';
import {
  Menu,
  X,
  Sun,
  Moon,
  Home,
  Box,
  Truck,
  PlusCircle,
  ShoppingCart,
  Clipboard,
} from 'lucide-vue-next';
import Sheet from '@/components/ui/sheet.vue';
import SheetTrigger from '@/components/ui/sheet-trigger.vue';
import SheetContent from '@/components/ui/sheet-content.vue';
import Button from '@/components/ui/button.vue';
import ScrollArea from '@/components/ui/scroll-area.vue';
import { LABELS } from '@/lib/constants/labels';

const route = useRoute();
const isOpen = ref(false);
const setIsOpen = (value: boolean) => {
  isOpen.value = value;
};

const isDark = useDark({
  selector: 'html',
  attribute: 'class',
  valueDark: 'dark',
  valueLight: '',
});

const toggleTheme = () => {
  isDark.value = !isDark.value;
};

const menuItems = [
  { name: LABELS.MENU_HOME || 'ホーム', iconComponent: Home, path: '/' },
  { name: LABELS.INVENTORY_CHECK || '在庫確認', iconComponent: Box, path: '/inventory' },
  { name: LABELS.REPLENISHMENT || '補充（移動）', iconComponent: Truck, path: '/replenishment' },
  { name: LABELS.CREATION || '補充（作成）', iconComponent: PlusCircle, path: '/creation' },
  { name: LABELS.ORDER_REQUEST || '発注依頼', iconComponent: ShoppingCart, path: '/order' },
  { name: LABELS.STATUS_LIST || '営業準備状況', iconComponent: Clipboard, path: '/status' },
];
</script>

// UniwaApp/operations-prepare/components/layout/main-layout.tsx
'use client';

import { useState, useEffect } from 'react';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import { Menu, X, Sun, Moon, Home, Box, Truck, PlusCircle, ShoppingCart, Clipboard } from 'lucide-react';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { useTheme } from 'next-themes';
import { ScrollArea } from "@/components/ui/scroll-area";
import { LABELS } from '@/lib/constants/labels';

interface MainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: MainLayoutProps) {
  const [isOpen, setIsOpen] = useState(false);
  const pathname = usePathname();
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  // Avoid hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  const menuItems = [
    { name: LABELS.MENU_HOME, icon: <Home className="h-5 w-5" />, path: '/' },
    { name: LABELS.INVENTORY_CHECK, icon: <Box className="h-5 w-5" />, path: '/inventory' },
    { name: LABELS.REPLENISHMENT, icon: <Truck className="h-5 w-5" />, path: '/replenishment' },
    { name: LABELS.CREATION, icon: <PlusCircle className="h-5 w-5" />, path: '/creation' },
    { name: LABELS.ORDER_REQUEST, icon: <ShoppingCart className="h-5 w-5" />, path: '/order' },
    { name: LABELS.STATUS_LIST, icon: <Clipboard className="h-5 w-5" />, path: '/status' },
  ];

  const toggleTheme = () => {
    setTheme(theme === 'dark' ? 'light' : 'dark');
  };

  return (
    <div className="flex flex-col min-h-screen">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-background border-b border-border">
        <div className="container flex items-center justify-between h-14 px-4">
          <div className="flex items-center gap-3">
            <Sheet open={isOpen} onOpenChange={setIsOpen}>
              <SheetTrigger asChild>
                <Button variant="ghost" size="icon" className="md:hidden">
                  <Menu className="h-5 w-5" />
                  <span className="sr-only">メニュー</span>
                </Button>
              </SheetTrigger>
              <SheetContent side="left" className="p-0">
                <div className="flex flex-col h-full">
                  <div className="p-4 border-b flex justify-between items-center">
                    <h2 className="text-lg font-medium">メニュー</h2>
                    <Button variant="ghost" size="icon" onClick={() => setIsOpen(false)}>
                      <X className="h-5 w-5" />
                    </Button>
                  </div>
                  <ScrollArea className="flex-1">
                    <nav className="px-2 py-4">
                      <ul className="space-y-2">
                        {menuItems.map((item) => (
                          <li key={item.path}>
                            <Link 
                              href={item.path}
                              onClick={() => setIsOpen(false)}
                              className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm transition-colors ${
                                pathname === item.path 
                                  ? 'bg-primary text-primary-foreground' 
                                  : 'hover:bg-secondary'
                              }`}
                            >
                              {item.icon}
                              {item.name}
                            </Link>
                          </li>
                        ))}
                      </ul>
                    </nav>
                  </ScrollArea>
                </div>
              </SheetContent>
            </Sheet>
            <h1 className="text-lg font-semibold">
              営業準備アプリ
            </h1>
          </div>
          <div className="flex items-center gap-2">
            {mounted && (
              <Button variant="ghost" size="icon" onClick={toggleTheme}>
                {theme === 'dark' ? (
                  <Sun className="h-5 w-5" />
                ) : (
                  <Moon className="h-5 w-5" />
                )}
                <span className="sr-only">テーマ切替</span>
              </Button>
            )}
          </div>
        </div>
      </header>

      {/* Main content */}
      <main className="flex-1 container px-4 py-4 max-w-lg mx-auto">
        {children}
      </main>

      {/* Mobile navigation */}
      <div className="md:hidden sticky bottom-0 z-40 bg-background border-t border-border">
        <nav className="flex items-center justify-around h-16">
          {menuItems.map((item) => (
            <Link 
              key={item.path}
              href={item.path}
              className={`flex flex-col items-center justify-center w-full h-full text-xs ${
                pathname === item.path 
                  ? 'text-primary' 
                  : 'text-muted-foreground'
              }`}
            >
              {item.icon}
              <span className="mt-1">{item.name}</span>
            </Link>
          ))}
        </nav>
      </div>
    </div>
  );
}
